
# Name of website
title: INICIO

# Your name to show in the footer
author: Oscar

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Sobre nosotros: "aboutus"
  Recursos:
    - Tetris: "https://chvin.github.io/react-tetris/?lan=en"
    - Ajedrez: "https://www.chess.com/es"
    - Como los Videojuegos pueden Ayudar a tu Mente: "https://youtu.be/ccIfRe5QF_4"
    - Centros de salud mental: "https://www.gob.pe/10942-conocer-los-centros-de-salud-mental-comunitaria-en-el-peru"

################
# --- Logo --- #
################
avatar: "/assets/img/avatar-icon.png"


round-avatar: true



social-network-links:
  rss: false  # remove this line if you don't want to show an RSS link at the bottom
  github: saludmental1


rss-description: This website is a virtual proof that I'm awesome

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  
url-pretty: "saludmental1.github.io"

excerpt_length: 50

feed_show_excerpt: false

feed_show_tags: false

post_search: false

edit_page_button: false

navbar-var-length: false


######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#242526"
navbar-text-col: "#e4e6eb"
navbar-border-col: "#DDDDDD"
page-col: "#18191a"
text-col: "#e4e6eb"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#242526"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "America/Lima"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap


